//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie_Vote.Content.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RGlobal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RGlobal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Movie_Vote.Content.Texts.RGlobal", typeof(RGlobal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ярославчик Інкорпорейтед.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про веб-сайт.
        /// </summary>
        public static string FooterAboutWebSite {
            get {
                return ResourceManager.GetString("FooterAboutWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подяки.
        /// </summary>
        public static string FooterCredits {
            get {
                return ResourceManager.GetString("FooterCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons8 за іконку сайту.
        /// </summary>
        public static string FooterCreditsIcons8 {
            get {
                return ResourceManager.GetString("FooterCreditsIcons8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Step за акаунт в Microsoft Imagine.
        /// </summary>
        public static string FooterCreditsItStep {
            get {
                return ResourceManager.GetString("FooterCreditsItStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft за Visual Studio, .Net та Azure.
        /// </summary>
        public static string FooterCreditsMicrosoft {
            get {
                return ResourceManager.GetString("FooterCreditsMicrosoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я тут.
        /// </summary>
        public static string FooterImHere {
            get {
                return ResourceManager.GetString("FooterImHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Особлива подяка.
        /// </summary>
        public static string FooterSpecialCredits {
            get {
                return ResourceManager.GetString("FooterSpecialCredits", resourceCulture);
            }
        }
    }
}
