//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie_Vote.Content.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RHome {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RHome() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Movie_Vote.Content.Texts.RHome", typeof(RHome).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фільтри.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додано.
        /// </summary>
        public static string FilterAdded {
            get {
                return ResourceManager.GetString("FilterAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нові.
        /// </summary>
        public static string FilterAddedNew {
            get {
                return ResourceManager.GetString("FilterAddedNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давні.
        /// </summary>
        public static string FilterAddedOld {
            get {
                return ResourceManager.GetString("FilterAddedOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додатково.
        /// </summary>
        public static string FilterExtra {
            get {
                return ResourceManager.GetString("FilterExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мої сердечка.
        /// </summary>
        public static string FilterExtraHeart {
            get {
                return ResourceManager.GetString("FilterExtraHeart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ярославчик рекомендує.
        /// </summary>
        public static string FilterExtraRecomend {
            get {
                return ResourceManager.GetString("FilterExtraRecomend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг.
        /// </summary>
        public static string FilterRating {
            get {
                return ResourceManager.GetString("FilterRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всі.
        /// </summary>
        public static string FilterRatingAll {
            get {
                return ResourceManager.GetString("FilterRatingAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Високий.
        /// </summary>
        public static string FilterRatingHigh {
            get {
                return ResourceManager.GetString("FilterRatingHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Низький.
        /// </summary>
        public static string FilterRatingLow {
            get {
                return ResourceManager.GetString("FilterRatingLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string FilterType {
            get {
                return ResourceManager.GetString("FilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всі.
        /// </summary>
        public static string FilterTypeAll {
            get {
                return ResourceManager.GetString("FilterTypeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фільми.
        /// </summary>
        public static string FilterTypeMovie {
            get {
                return ResourceManager.GetString("FilterTypeMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серіали.
        /// </summary>
        public static string FilterTypeTv {
            get {
                return ResourceManager.GetString("FilterTypeTv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанри.
        /// </summary>
        public static string MovieInfoGenres {
            get {
                return ResourceManager.GetString("MovieInfoGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва.
        /// </summary>
        public static string MovieInfoName {
            get {
                return ResourceManager.GetString("MovieInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реліз.
        /// </summary>
        public static string MovieInfoRelease {
            get {
                return ResourceManager.GetString("MovieInfoRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фільм.
        /// </summary>
        public static string MovieTypeMovie {
            get {
                return ResourceManager.GetString("MovieTypeMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серіал.
        /// </summary>
        public static string MovieTypeTv {
            get {
                return ResourceManager.GetString("MovieTypeTv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переглянуті мною фільми.
        /// </summary>
        public static string TitleLine1 {
            get {
                return ResourceManager.GetString("TitleLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Голосуй за найкращий!.
        /// </summary>
        public static string TitleLine2 {
            get {
                return ResourceManager.GetString("TitleLine2", resourceCulture);
            }
        }
    }
}
